name = "dgc-lead-worker"
main = "index.js"
compatibility_date = "2025-02-24"

[vars]
GOOGLE_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbxAf5dFOEDIBSi7Fum1oVYT06G5JXUMUhyljQDiU9EwvYoaKW2pR7rJy2yC4F5Rriz4/exec"
FORMSPREE_URL = "https://formspree.io/f/mqedlzen"
ADMIN_EMAIL = "admin@dahangroup.io"
