name = "dgc-chat-api"
main = "index.js"
compatibility_date = "2025-02-24"

[vars]
FORMSPREE_URL = "https://formspree.io/f/mqedlzen"
GOOGLE_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbxAf5dFOEDIBSi7Fum1oVYT06G5JXUMUhyljQDiU9EwvYoaKW2pR7rJy2yC4F5Rriz4/exec"
ADMIN_EMAIL = "admin@dahangroup.io"
LEAD_WORKER_URL = "https://dgc-lead-worker.ericdahan10.workers.dev"
